const categoryImages = {
  "dried-flower": "/assets/img/Dashboard%20HCP/category%20images/Our%20Product%20Range-Dried%20Flower.webp",
  "oral-liquid": "/assets/img/Dashboard%20HCP/category%20images/Our%20Product%20Range-Oral%20Liquid.webp",
  pastilles: "/assets/img/Dashboard%20HCP/category%20images/Our%20Product%20Range-Pastilles.webp",
  "inhaled-liquid": "/assets/img/Dashboard%20HCP/category%20images/Our%20Product%20Range-Inhaled%20Liquid.webp",
};

const categoryMeta = {
  "dried-flower": {
    categoryName: "Dried Flower",
    dosageForm: "Dried Flower",
    presentation: "Dried flower in sealed container",
  },
  "oral-liquid": {
    categoryName: "Oral Liquid",
    dosageForm: "Oral Liquid",
    presentation: "Oral liquid in amber glass bottle with dropper",
  },
  pastilles: {
    categoryName: "Pastilles",
    dosageForm: "Pastilles",
    presentation: "Pastilles in child-resistant pack",
  },
  "inhaled-liquid": {
    categoryName: "Inhaled Liquid",
    dosageForm: "Inhaled Liquid",
    presentation: "Inhaled liquid cartridge (1 g)",
  },
};

function slugify(name) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

function productImages(folder, count) {
  const base = "/assets/img/Dashboard%20HCP/products/" + folder.split("/").map(encodeURIComponent).join("/");
  const images = [];
  for (let i = 1; i <= count; i++) images.push(base + "/" + i + ".webp");
  return images;
}

function buildProduct({
  name,
  categorySlug,
  thc,
  cbd,
  cbg,
  cbn,
  packSize,
  price,
  strainType,
  speciesRatio,
  cultivar,
  tgaCategory,
  schedule,
  spectrum,
  excipients,
  flavour,
  dietaryTags,
  dominantTerpenes,
  therapeuticProfile,
  strength,
  images,
  energyKj,
  sugars,
  carbs,
  sodium,
  fat,
}) {
  const meta = categoryMeta[categorySlug];
  return {
    slug: slugify(name),
    name,
    categorySlug,
    category: meta.categoryName,
    dosageForm: meta.dosageForm,
    thc: thc || "",
    cbd: cbd || "",
    cbg: cbg || "",
    cbn: cbn || "",
    packSize,
    price,
    strength: strength || "",
    strainType: strainType || "",
    speciesRatio: speciesRatio || "",
    cultivar: cultivar || "",
    presentation: meta.presentation,
    dominantTerpenes: dominantTerpenes || "",
    excipients: excipients || "",
    therapeuticProfile: therapeuticProfile || "",
    tgaCategory: tgaCategory || "",
    schedule: schedule || "",
    spectrum: spectrum || "",
    flavour: flavour || "",
    dietaryTags: dietaryTags || "",
    energyKj: energyKj || "",
    sugars: sugars || "",
    carbs: carbs || "",
    sodium: sodium || "",
    fat: fat || "",
    images: images || [],
    image: (images && images[0]) || categoryImages[categorySlug],
    altImage: (images && images[1]) || (images && images[0]) || categoryImages[categorySlug],
  };
}

export const products = [
  buildProduct({
    name: "Noosa Selects T19 Hybrid",
    categorySlug: "dried-flower",
    thc: "19%",
    cbd: "<1%",
    packSize: "15g",
    price: "99",
    strength: "thc",
    strainType: "Hybrid",
    speciesRatio: "Indica 50% : Sativa 50%",
    cultivar: "Afternoon Tea",
    dominantTerpenes: "Myrcene, β-Caryophyllene, α-Humulene",
    therapeuticProfile: "Anxiety, Chronic Pain, ADHD, Cancer Pain, Fibromyalgia",
    tgaCategory: "Category 5",
    schedule: "Schedule 8 (S8)",
    images: productImages("Dried-flower/Noosa Selects T19 Hybrid", 4),
  }),
  buildProduct({
    name: "Noosa Selects T21 Indica",
    categorySlug: "dried-flower",
    thc: "21%",
    cbd: "<1%",
    packSize: "15g",
    price: "99",
    strength: "thc",
    strainType: "Indica",
    speciesRatio: "Indica 60% : Sativa 40%",
    cultivar: "Chocolate Cherry",
    dominantTerpenes: "Myrcene, β-Caryophyllene, α-Pinene",
    therapeuticProfile: "Chronic Pain, Anxiety, PTSD, Muscle Spasm, Stress Disorders",
    tgaCategory: "Category 5",
    schedule: "Schedule 8 (S8)",
    images: productImages("Dried-flower/Noosa Selects T21 Indica", 4),
  }),
  buildProduct({
    name: "Noosa Selects T25 Sativa",
    categorySlug: "dried-flower",
    thc: "25%",
    cbd: "<1%",
    packSize: "15g",
    price: "99",
    strength: "thc",
    strainType: "Sativa",
    speciesRatio: "Indica 30% : Sativa 70%",
    cultivar: "Platinum GDP",
    dominantTerpenes: "Myrcene, Terpinolene, Limonene",
    tgaCategory: "Category 5",
    schedule: "Schedule 8 (S8)",
    images: productImages("Dried-flower/Noosa Selects T25 Sativa", 4),
  }),
  buildProduct({
    name: "Serene 200 Isolate",
    categorySlug: "oral-liquid",
    cbd: "200mg/mL",
    packSize: "30mL bottle",
    price: "112",
    strength: "cbd",
    spectrum: "Isolate",
    tgaCategory: "Category 1",
    schedule: "Schedule 4 (S4)",
    images: productImages("ORAL LIQUID/Serene 200 Isolate", 4),
  }),
  buildProduct({
    name: "Serene 200 Plus",
    categorySlug: "oral-liquid",
    cbd: "200mg/mL",
    cbg: "<2mg/mL",
    cbn: "<2mg/mL",
    packSize: "30mL bottle",
    price: "112",
    strength: "cbd",
    spectrum: "Broad Spectrum",
    tgaCategory: "Category 1",
    schedule: "Schedule 4 (S4)",
    images: productImages("ORAL LIQUID/Serene 200 Plus", 4),
  }),
  buildProduct({
    name: "PharmaCrop Horizon 30:30",
    categorySlug: "oral-liquid",
    thc: "30mg/mL",
    cbd: "30mg/mL",
    packSize: "30mL bottle",
    price: "99",
    strength: "balanced",
    spectrum: "Balanced Full Spectrum",
    tgaCategory: "Category 3",
    schedule: "Schedule 8 (S8)",
    images: productImages("ORAL LIQUID/Oral Liquid Horizon 30-30", 4),
  }),
  buildProduct({
    name: "PharmaCrop 20:20:20 Night",
    categorySlug: "pastilles",
    thc: "20mg",
    cbd: "20mg",
    cbn: "20mg",
    packSize: "60 pastilles",
    price: "99",
    strength: "balanced",
    flavour: "Blueberry",
    dietaryTags: "Gluten Free | Vegan Friendly | Halal",
    tgaCategory: "Category 4",
    schedule: "Schedule 8 (S8)",
    energyKj: "37.5",
    sugars: "1.5",
    carbs: "2.19",
    sodium: "7.8",
    fat: "<0.01",
    images: productImages("PSTILLES", 4),
  }),
  buildProduct({
    name: "PharmaCrop Luminous",
    categorySlug: "inhaled-liquid",
    thc: "750mg",
    cbd: "<1%",
    packSize: "1g cartridge",
    price: "99",
    strength: "thc",
    strainType: "Sativa",
    cultivar: "Pineapple Express",
    dominantTerpenes: "β-Caryophyllene, Myrcene, β-Pinene",
    tgaCategory: "Category 5",
    schedule: "Schedule 8 (S8)",
    images: productImages("Inhaled Liquid/Inhaled Liquid-PharmaCrop Luminous", 4),
  }),
  buildProduct({
    name: "PharmaCrop Daydream",
    categorySlug: "inhaled-liquid",
    thc: "850mg",
    cbd: "<1%",
    cbg: "25mg",
    cbn: "20mg",
    packSize: "1g cartridge",
    price: "99",
    strength: "thc",
    strainType: "Sativa",
    cultivar: "Jack Herer",
    dominantTerpenes: "Terpinolene, Myrcene, Ocimene",
    tgaCategory: "Category 5",
    schedule: "Schedule 8 (S8)",
    images: productImages("Inhaled Liquid/PharmaCrop Daydream", 4),
  }),
];
